language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.4.1
    - otp_release: 19.0
      elixir: 1.3.2
sudo: false
notifications:
  email: false
before_script:
  # Set download location
  - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  # Download PLT from danielberkompas/travis_elixir_plts on Github
  # Store in $PLT_LOCATION
  - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
  - mix test
  - mix credo --strict
  - dialyzer --no_check_plt --plt $PLT_LOCATION --no_native _build/test/lib/slime/ebin
